package com.simats.pathovision.repository

import com.simats.pathovision.models.CaseItem
import com.simats.pathovision.models.GenerateReportResponse
import com.simats.pathovision.models.SignOffResponse
import com.simats.pathovision.network.ApiService
import com.simats.pathovision.utils.Resource
import javax.inject.Inject

class CaseRepository @Inject constructor(
    private val apiService: ApiService
) {
    suspend fun getCases(): Resource<List<CaseItem>> {
        return try {
            val response = apiService.getCases()
            if (response.isSuccessful && response.body() != null) {
                Resource.Success(response.body()!!)
            } else {
                val errorBody = response.errorBody()?.string()
                Resource.Error(errorBody ?: "Failed to load cases.")
            }
        } catch (e: Exception) {
            Resource.Error(e.message ?: "Unable to connect to server.")
        }
    }

    suspend fun createCase(
        patientId: String,
        tissueType: String,
        clinicalNotes: String?
    ): Resource<CaseItem> {
        return try {
            val request = com.simats.pathovision.models.CreateCaseRequest(
                title = "", // Will be auto-generated by backend
                doctor_notes = "Tissue Type: $tissueType${if (!clinicalNotes.isNullOrBlank()) "\n\nClinical Notes: $clinicalNotes" else ""}",
                patient_id = patientId
            )
            val response = apiService.createCase(request)
            if (response.isSuccessful && response.body() != null) {
                Resource.Success(response.body()!!)
            } else {
                val errorBody = response.errorBody()?.string()
                Resource.Error(errorBody ?: "Failed to create case.")
            }
        } catch (e: Exception) {
            Resource.Error(e.message ?: "Unable to connect to server.")
        }
    }

    suspend fun generateReport(caseId: String): Resource<GenerateReportResponse> {
        return try {
            val response = apiService.generateReport(caseId)
            if (response.isSuccessful && response.body() != null) {
                Resource.Success(response.body()!!)
            } else {
                val errorBody = response.errorBody()?.string()
                Resource.Error(errorBody ?: "Failed to generate report.")
            }
        } catch (e: Exception) {
            Resource.Error(e.message ?: "Unable to connect to server.")
        }
    }

    suspend fun signOffReport(caseId: String): Resource<SignOffResponse> {
        return try {
            val response = apiService.signOffReport(caseId)
            if (response.isSuccessful && response.body() != null) {
                Resource.Success(response.body()!!)
            } else {
                val errorBody = response.errorBody()?.string()
                Resource.Error(errorBody ?: "Failed to sign off report.")
            }
        } catch (e: Exception) {
            Resource.Error(e.message ?: "Unable to connect to server.")
        }
    }
}
